# Generated by Django 4.2.2 on 2023-09-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementprogram', '0003_member_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='salary',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='emailid',
            field=models.CharField(max_length=200),
        ),
    ]
