# Generated by Django 4.2.2 on 2023-09-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementprogram', '0004_member_last_name_member_salary_alter_member_emailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
